# Generated by Django 4.2.1 on 2023-07-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
