# Generated by Django 4.2.1 on 2023-07-10 08:13

from django.db import migrations, models
import product_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product_shop.models.upload_to),
        ),
    ]
